#!/bin/bash
# analyze_henry-v.sh - Analyze the entirety of Henry V
# Generated by /analyze-plays command
#
# Usage: ./analyze_henry-v.sh [--dry-run]
#
# Structure discovered:
#   - Opening Prologue: Yes
#   - Acts: 1, 2, 3, 4, 5
#   - Epilogue: Yes
#   - Total output files: 29

PLAY="/home/mlj/utono/literature/shakespeare-william/gutenberg/henry_v_gut.txt"
ANALYZER=~/utono/nvim-glosses-qa/python/scene_analyzer.py
MERGE=42
LOG_FILE=~/utono/nvim-glosses-qa/logs/scene_analyzer.log
DRY_RUN=""

# Check for --dry-run flag
if [ "$1" = "--dry-run" ] || [ "$1" = "-n" ]; then
    DRY_RUN="--dry-run"
    echo "=== DRY RUN MODE ==="
fi

# Clear log file at start of run
mkdir -p "$(dirname "$LOG_FILE")"
> "$LOG_FILE"
echo "Log cleared: $LOG_FILE"

echo "Analyzing Henry V..."
echo "Play file: $PLAY"
echo "Merge threshold: $MERGE lines"
echo "Log file: $LOG_FILE"
echo ""

# Opening Prologue (act 0, scene 0)
echo "--- Prologue (Opening) ---"
python "$ANALYZER" "$PLAY" 0 0 --merge "$MERGE" $DRY_RUN

# Act 1, Scene 1
echo "--- Act 1, Scene 1 ---"
python "$ANALYZER" "$PLAY" 1 1 --merge "$MERGE" $DRY_RUN

# Act 1, Scene 2
echo "--- Act 1, Scene 2 ---"
python "$ANALYZER" "$PLAY" 1 2 --merge "$MERGE" $DRY_RUN

# Act 2 Prologue (act 2, scene 0)
echo "--- Act 2, Prologue ---"
python "$ANALYZER" "$PLAY" 2 0 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 1
echo "--- Act 2, Scene 1 ---"
python "$ANALYZER" "$PLAY" 2 1 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 2
echo "--- Act 2, Scene 2 ---"
python "$ANALYZER" "$PLAY" 2 2 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 3
echo "--- Act 2, Scene 3 ---"
python "$ANALYZER" "$PLAY" 2 3 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 4
echo "--- Act 2, Scene 4 ---"
python "$ANALYZER" "$PLAY" 2 4 --merge "$MERGE" $DRY_RUN

# Act 3 Prologue (act 3, scene 0)
echo "--- Act 3, Prologue ---"
python "$ANALYZER" "$PLAY" 3 0 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 1
echo "--- Act 3, Scene 1 ---"
python "$ANALYZER" "$PLAY" 3 1 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 2
echo "--- Act 3, Scene 2 ---"
python "$ANALYZER" "$PLAY" 3 2 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 3
echo "--- Act 3, Scene 3 ---"
python "$ANALYZER" "$PLAY" 3 3 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 4
echo "--- Act 3, Scene 4 ---"
python "$ANALYZER" "$PLAY" 3 4 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 5
echo "--- Act 3, Scene 5 ---"
python "$ANALYZER" "$PLAY" 3 5 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 6
echo "--- Act 3, Scene 6 ---"
python "$ANALYZER" "$PLAY" 3 6 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 7
echo "--- Act 3, Scene 7 ---"
python "$ANALYZER" "$PLAY" 3 7 --merge "$MERGE" $DRY_RUN

# Act 4 Prologue (act 4, scene 0)
echo "--- Act 4, Prologue ---"
python "$ANALYZER" "$PLAY" 4 0 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 1
echo "--- Act 4, Scene 1 ---"
python "$ANALYZER" "$PLAY" 4 1 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 2
echo "--- Act 4, Scene 2 ---"
python "$ANALYZER" "$PLAY" 4 2 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 3
echo "--- Act 4, Scene 3 ---"
python "$ANALYZER" "$PLAY" 4 3 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 4
echo "--- Act 4, Scene 4 ---"
python "$ANALYZER" "$PLAY" 4 4 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 5
echo "--- Act 4, Scene 5 ---"
python "$ANALYZER" "$PLAY" 4 5 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 6
echo "--- Act 4, Scene 6 ---"
python "$ANALYZER" "$PLAY" 4 6 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 7
echo "--- Act 4, Scene 7 ---"
python "$ANALYZER" "$PLAY" 4 7 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 8
echo "--- Act 4, Scene 8 ---"
python "$ANALYZER" "$PLAY" 4 8 --merge "$MERGE" $DRY_RUN

# Act 5 Prologue (act 5, scene 0)
echo "--- Act 5, Prologue ---"
python "$ANALYZER" "$PLAY" 5 0 --merge "$MERGE" $DRY_RUN

# Act 5, Scene 1
echo "--- Act 5, Scene 1 ---"
python "$ANALYZER" "$PLAY" 5 1 --merge "$MERGE" $DRY_RUN

# Act 5, Scene 2
echo "--- Act 5, Scene 2 ---"
python "$ANALYZER" "$PLAY" 5 2 --merge "$MERGE" $DRY_RUN

# Epilogue (act 6, scene 0)
echo "--- Epilogue ---"
python "$ANALYZER" "$PLAY" 6 0 --merge "$MERGE" $DRY_RUN

echo ""
echo "=== Complete ==="
echo "Output directory: ~/utono/literature/glosses/henry-v/"
