#!/bin/bash
# analyze_merchant-of-venice.sh - Analyze the entirety of Merchant Of Venice
# Generated by /analyze-plays command
#
# Usage: ./analyze_merchant-of-venice.sh [--dry-run]
#
# Structure discovered:
#   - Opening Prologue: No
#   - Acts: 5
#   - Epilogue: No
#   - Total output files: 1

PLAY="/home/mlj/utono/literature/shakespeare-william/gutenberg/merchant_of_venice_gut.txt"
ANALYZER=~/utono/nvim-glosses-qa/python/scene_analyzer.py
MERGE=42
LOG_FILE=~/utono/nvim-glosses-qa/logs/scene_analyzer.log
DRY_RUN=""

# Check for --dry-run flag
if [ "$1" = "--dry-run" ] || [ "$1" = "-n" ]; then
    DRY_RUN="--dry-run"
    echo "=== DRY RUN MODE ==="
fi

# Clear log file at start of run
mkdir -p "$(dirname "$LOG_FILE")"
> "$LOG_FILE"
echo "Log cleared: $LOG_FILE"

echo "Analyzing Merchant Of Venice..."
echo "Play file: $PLAY"
echo "Merge threshold: $MERGE lines"
echo "Log file: $LOG_FILE"
echo ""

# Act 5, Scene 1
echo "--- Act 5, Scene 1 ---"
python "$ANALYZER" "$PLAY" 5 1 --merge "$MERGE" $DRY_RUN

echo ""
echo "=== Complete ==="
echo "Output directory: ~/utono/literature/glosses/merchant-of-venice/"
