#!/bin/bash
# analyze_antony-and-cleopatra.sh - Analyze the entirety of Antony And Cleopatra
# Generated by /analyze-plays command
#
# Usage: ./analyze_antony-and-cleopatra.sh [--dry-run]
#
# Structure discovered:
#   - Opening Prologue: No
#   - Acts: 1, 2, 3, 5
#   - Epilogue: No
#   - Total output files: 29

PLAY="/home/mlj/utono/literature/shakespeare-william/gutenberg/antony_and_cleopatra_gut.txt"
ANALYZER=~/utono/nvim-glosses-qa/python/scene_analyzer.py
MERGE=42
LOG_FILE=~/utono/nvim-glosses-qa/logs/scene_analyzer.log
DRY_RUN=""

# Check for --dry-run flag
if [ "$1" = "--dry-run" ] || [ "$1" = "-n" ]; then
    DRY_RUN="--dry-run"
    echo "=== DRY RUN MODE ==="
fi

# Clear log file at start of run
mkdir -p "$(dirname "$LOG_FILE")"
> "$LOG_FILE"
echo "Log cleared: $LOG_FILE"

echo "Analyzing Antony And Cleopatra..."
echo "Play file: $PLAY"
echo "Merge threshold: $MERGE lines"
echo "Log file: $LOG_FILE"
echo ""

# Act 1, Scene 1
echo "--- Act 1, Scene 1 ---"
python "$ANALYZER" "$PLAY" 1 1 --merge "$MERGE" $DRY_RUN

# Act 1, Scene 2
echo "--- Act 1, Scene 2 ---"
python "$ANALYZER" "$PLAY" 1 2 --merge "$MERGE" $DRY_RUN

# Act 1, Scene 3
echo "--- Act 1, Scene 3 ---"
python "$ANALYZER" "$PLAY" 1 3 --merge "$MERGE" $DRY_RUN

# Act 1, Scene 4
echo "--- Act 1, Scene 4 ---"
python "$ANALYZER" "$PLAY" 1 4 --merge "$MERGE" $DRY_RUN

# Act 1, Scene 5
echo "--- Act 1, Scene 5 ---"
python "$ANALYZER" "$PLAY" 1 5 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 1
echo "--- Act 2, Scene 1 ---"
python "$ANALYZER" "$PLAY" 2 1 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 2
echo "--- Act 2, Scene 2 ---"
python "$ANALYZER" "$PLAY" 2 2 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 3
echo "--- Act 2, Scene 3 ---"
python "$ANALYZER" "$PLAY" 2 3 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 4
echo "--- Act 2, Scene 4 ---"
python "$ANALYZER" "$PLAY" 2 4 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 5
echo "--- Act 2, Scene 5 ---"
python "$ANALYZER" "$PLAY" 2 5 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 6
echo "--- Act 2, Scene 6 ---"
python "$ANALYZER" "$PLAY" 2 6 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 7
echo "--- Act 2, Scene 7 ---"
python "$ANALYZER" "$PLAY" 2 7 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 1
echo "--- Act 3, Scene 1 ---"
python "$ANALYZER" "$PLAY" 3 1 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 2
echo "--- Act 3, Scene 2 ---"
python "$ANALYZER" "$PLAY" 3 2 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 3
echo "--- Act 3, Scene 3 ---"
python "$ANALYZER" "$PLAY" 3 3 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 4
echo "--- Act 3, Scene 4 ---"
python "$ANALYZER" "$PLAY" 3 4 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 5
echo "--- Act 3, Scene 5 ---"
python "$ANALYZER" "$PLAY" 3 5 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 6
echo "--- Act 3, Scene 6 ---"
python "$ANALYZER" "$PLAY" 3 6 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 7
echo "--- Act 3, Scene 7 ---"
python "$ANALYZER" "$PLAY" 3 7 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 8
echo "--- Act 3, Scene 8 ---"
python "$ANALYZER" "$PLAY" 3 8 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 9
echo "--- Act 3, Scene 9 ---"
python "$ANALYZER" "$PLAY" 3 9 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 10
echo "--- Act 3, Scene 10 ---"
python "$ANALYZER" "$PLAY" 3 10 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 11
echo "--- Act 3, Scene 11 ---"
python "$ANALYZER" "$PLAY" 3 11 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 12
echo "--- Act 3, Scene 12 ---"
python "$ANALYZER" "$PLAY" 3 12 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 13
echo "--- Act 3, Scene 13 ---"
python "$ANALYZER" "$PLAY" 3 13 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 14
echo "--- Act 3, Scene 14 ---"
python "$ANALYZER" "$PLAY" 3 14 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 15
echo "--- Act 3, Scene 15 ---"
python "$ANALYZER" "$PLAY" 3 15 --merge "$MERGE" $DRY_RUN

# Act 5, Scene 1
echo "--- Act 5, Scene 1 ---"
python "$ANALYZER" "$PLAY" 5 1 --merge "$MERGE" $DRY_RUN

# Act 5, Scene 2
echo "--- Act 5, Scene 2 ---"
python "$ANALYZER" "$PLAY" 5 2 --merge "$MERGE" $DRY_RUN

echo ""
echo "=== Complete ==="
echo "Output directory: ~/utono/literature/glosses/antony-and-cleopatra/"
