#!/bin/bash
# analyze_alls-well-that-ends-well.sh - Analyze the entirety of Alls Well That Ends Well
# Generated by /analyze-plays command
#
# Usage: ./analyze_alls-well-that-ends-well.sh [--dry-run]
#
# Structure discovered:
#   - Opening Prologue: No
#   - Acts: 1, 2, 3, 4, 5
#   - Epilogue: No
#   - Total output files: 0

PLAY="/home/mlj/utono/literature/shakespeare-william/gutenberg/alls_well_that_ends_well_gut.txt"
ANALYZER=~/utono/nvim-glosses-qa/python/scene_analyzer.py
MERGE=42
LOG_FILE=~/utono/nvim-glosses-qa/logs/scene_analyzer.log
DRY_RUN=""

# Check for --dry-run flag
if [ "$1" = "--dry-run" ] || [ "$1" = "-n" ]; then
    DRY_RUN="--dry-run"
    echo "=== DRY RUN MODE ==="
fi

# Clear log file at start of run
mkdir -p "$(dirname "$LOG_FILE")"
> "$LOG_FILE"
echo "Log cleared: $LOG_FILE"

echo "Analyzing Alls Well That Ends Well..."
echo "Play file: $PLAY"
echo "Merge threshold: $MERGE lines"
echo "Log file: $LOG_FILE"
echo ""

echo ""
echo "=== Complete ==="
echo "Output directory: ~/utono/literature/glosses/alls-well-that-ends-well/"
