#!/bin/bash
# analyze_midsummer-nights-dream.sh - Analyze the entirety of Midsummer Nights Dream
# Generated by /analyze-plays command
#
# Usage: ./analyze_midsummer-nights-dream.sh [--dry-run]
#
# Structure discovered:
#   - Opening Prologue: No
#   - Acts: 1, 2, 3, 4, 5
#   - Epilogue: No
#   - Total output files: 10

PLAY="/home/mlj/utono/literature/shakespeare-william/gutenberg/midsummer_nights_dream_gut.txt"
ANALYZER=~/utono/nvim-glosses-qa/python/scene_analyzer.py
MERGE=15
DRY_RUN=""

# Check for --dry-run flag
if [ "$1" = "--dry-run" ] || [ "$1" = "-n" ]; then
    DRY_RUN="--dry-run"
    echo "=== DRY RUN MODE ==="
fi

echo "Analyzing Midsummer Nights Dream..."
echo "Play file: $PLAY"
echo "Merge threshold: $MERGE lines"
echo ""

# Act 1, Scene 1
echo "--- Act 1, Scene 1 ---"
python "$ANALYZER" "$PLAY" 1 1 --merge "$MERGE" $DRY_RUN

# Act 1, Scene 2
echo "--- Act 1, Scene 2 ---"
python "$ANALYZER" "$PLAY" 1 2 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 1
echo "--- Act 2, Scene 1 ---"
python "$ANALYZER" "$PLAY" 2 1 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 2
echo "--- Act 2, Scene 2 ---"
python "$ANALYZER" "$PLAY" 2 2 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 1
echo "--- Act 3, Scene 1 ---"
python "$ANALYZER" "$PLAY" 3 1 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 2
echo "--- Act 3, Scene 2 ---"
python "$ANALYZER" "$PLAY" 3 2 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 1
echo "--- Act 4, Scene 1 ---"
python "$ANALYZER" "$PLAY" 4 1 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 2
echo "--- Act 4, Scene 2 ---"
python "$ANALYZER" "$PLAY" 4 2 --merge "$MERGE" $DRY_RUN

# Act 5 Prologue (act 5, scene 0)
echo "--- Act 5, Prologue ---"
python "$ANALYZER" "$PLAY" 5 0 --merge "$MERGE" $DRY_RUN

# Act 5, Scene 1
echo "--- Act 5, Scene 1 ---"
python "$ANALYZER" "$PLAY" 5 1 --merge "$MERGE" $DRY_RUN

echo ""
echo "=== Complete ==="
echo "Output directory: ~/utono/literature/glosses/midsummer-nights-dream/"
