#!/bin/bash
# analyze_henry-v.sh - Analyze the entirety of Henry V
# Generated by /analyze-play command
#
# Usage: ./analyze_henry-v.sh [--dry-run]
#
# Structure discovered:
#   - Opening Prologue: yes
#   - Act 1: 2 scenes
#   - Act 2: Prologue + 4 scenes
#   - Act 3: Prologue + 7 scenes
#   - Act 4: Prologue + 8 scenes
#   - Act 5: Prologue + 2 scenes
#   - Epilogue: yes
#   - Total output files: 28

PLAY=~/utono/literature/shakespeare-william/gutenberg/henry_v_gut.txt
ANALYZER=~/utono/nvim-glosses-qa/python/scene_analyzer.py
MERGE=15
DRY_RUN=""

# Check for --dry-run flag
if [ "$1" = "--dry-run" ] || [ "$1" = "-n" ]; then
    DRY_RUN="--dry-run"
    echo "=== DRY RUN MODE ==="
fi

echo "Analyzing Henry V..."
echo "Play file: $PLAY"
echo "Merge threshold: $MERGE lines"
echo ""

# Opening Prologue
echo "=== Opening Prologue ==="
echo "--- Prologue (Opening) ---"
python "$ANALYZER" "$PLAY" 0 0 --merge "$MERGE" $DRY_RUN

# Act 1: 2 scenes (no prologue)
echo ""
echo "=== Act 1 ==="
for scene in 1 2; do
    echo "--- Act 1, Scene $scene ---"
    python "$ANALYZER" "$PLAY" 1 $scene --merge "$MERGE" $DRY_RUN
done

# Act 2: Prologue + 4 scenes
echo ""
echo "=== Act 2 ==="
echo "--- Act 2, Prologue ---"
python "$ANALYZER" "$PLAY" 2 0 --merge "$MERGE" $DRY_RUN
for scene in 1 2 3 4; do
    echo "--- Act 2, Scene $scene ---"
    python "$ANALYZER" "$PLAY" 2 $scene --merge "$MERGE" $DRY_RUN
done

# Act 3: Prologue + 7 scenes
echo ""
echo "=== Act 3 ==="
echo "--- Act 3, Prologue ---"
python "$ANALYZER" "$PLAY" 3 0 --merge "$MERGE" $DRY_RUN
for scene in 1 2 3 4 5 6 7; do
    echo "--- Act 3, Scene $scene ---"
    python "$ANALYZER" "$PLAY" 3 $scene --merge "$MERGE" $DRY_RUN
done

# Act 4: Prologue + 8 scenes
echo ""
echo "=== Act 4 ==="
echo "--- Act 4, Prologue ---"
python "$ANALYZER" "$PLAY" 4 0 --merge "$MERGE" $DRY_RUN
for scene in 1 2 3 4 5 6 7 8; do
    echo "--- Act 4, Scene $scene ---"
    python "$ANALYZER" "$PLAY" 4 $scene --merge "$MERGE" $DRY_RUN
done

# Act 5: Prologue + 2 scenes
echo ""
echo "=== Act 5 ==="
echo "--- Act 5, Prologue ---"
python "$ANALYZER" "$PLAY" 5 0 --merge "$MERGE" $DRY_RUN
for scene in 1 2; do
    echo "--- Act 5, Scene $scene ---"
    python "$ANALYZER" "$PLAY" 5 $scene --merge "$MERGE" $DRY_RUN
done

# Epilogue
echo ""
echo "=== Epilogue ==="
echo "--- Epilogue ---"
python "$ANALYZER" "$PLAY" 0 -1 --merge "$MERGE" $DRY_RUN

echo ""
echo "=== Complete ==="
echo "Output directory: ~/utono/literature/glosses/henry-v/"
