#!/bin/bash
# analyze_henry-viii.sh - Analyze the entirety of Henry Viii
# Generated by /analyze-plays command
#
# Usage: ./analyze_henry-viii.sh [--dry-run]
#
# Structure discovered:
#   - Opening Prologue: No
#   - Acts: 1, 2
#   - Epilogue: No
#   - Total output files: 8

PLAY="/home/mlj/utono/literature/shakespeare-william/gutenberg/henry_viii_gut.txt"
ANALYZER=~/utono/nvim-glosses-qa/python/scene_analyzer.py
MERGE=42
LOG_FILE=~/utono/nvim-glosses-qa/logs/scene_analyzer.log
DRY_RUN=""

# Check for --dry-run flag
if [ "$1" = "--dry-run" ] || [ "$1" = "-n" ]; then
    DRY_RUN="--dry-run"
    echo "=== DRY RUN MODE ==="
fi

# Clear log file at start of run
mkdir -p "$(dirname "$LOG_FILE")"
> "$LOG_FILE"
echo "Log cleared: $LOG_FILE"

echo "Analyzing Henry Viii..."
echo "Play file: $PLAY"
echo "Merge threshold: $MERGE lines"
echo "Log file: $LOG_FILE"
echo ""

# Act 1, Scene 2
echo "--- Act 1, Scene 2 ---"
python "$ANALYZER" "$PLAY" 1 2 --merge "$MERGE" $DRY_RUN

# Act 1, Scene 3
echo "--- Act 1, Scene 3 ---"
python "$ANALYZER" "$PLAY" 1 3 --merge "$MERGE" $DRY_RUN

# Act 1, Scene 4
echo "--- Act 1, Scene 4 ---"
python "$ANALYZER" "$PLAY" 1 4 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 1
echo "--- Act 2, Scene 1 ---"
python "$ANALYZER" "$PLAY" 2 1 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 2
echo "--- Act 2, Scene 2 ---"
python "$ANALYZER" "$PLAY" 2 2 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 3
echo "--- Act 2, Scene 3 ---"
python "$ANALYZER" "$PLAY" 2 3 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 4
echo "--- Act 2, Scene 4 ---"
python "$ANALYZER" "$PLAY" 2 4 --merge "$MERGE" $DRY_RUN

# Act 2, Scene 5
echo "--- Act 2, Scene 5 ---"
python "$ANALYZER" "$PLAY" 2 5 --merge "$MERGE" $DRY_RUN

echo ""
echo "=== Complete ==="
echo "Output directory: ~/utono/literature/glosses/henry-viii/"
