#!/bin/bash
# analyze_henry-vi-part-2.sh - Analyze the entirety of Henry Vi Part 2
# Generated by /analyze-plays command
#
# Usage: ./analyze_henry-vi-part-2.sh [--dry-run]
#
# Structure discovered:
#   - Opening Prologue: No
#   - Acts: 3, 4, 5
#   - Epilogue: No
#   - Total output files: 16

PLAY="/home/mlj/utono/literature/shakespeare-william/gutenberg/henry_vi_part_2_gut.txt"
ANALYZER=~/utono/nvim-glosses-qa/python/scene_analyzer.py
MERGE=42
LOG_FILE=~/utono/nvim-glosses-qa/logs/scene_analyzer.log
DRY_RUN=""

# Check for --dry-run flag
if [ "$1" = "--dry-run" ] || [ "$1" = "-n" ]; then
    DRY_RUN="--dry-run"
    echo "=== DRY RUN MODE ==="
fi

# Clear log file at start of run
mkdir -p "$(dirname "$LOG_FILE")"
> "$LOG_FILE"
echo "Log cleared: $LOG_FILE"

echo "Analyzing Henry Vi Part 2..."
echo "Play file: $PLAY"
echo "Merge threshold: $MERGE lines"
echo "Log file: $LOG_FILE"
echo ""

# Act 3, Scene 1
echo "--- Act 3, Scene 1 ---"
python "$ANALYZER" "$PLAY" 3 1 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 2
echo "--- Act 3, Scene 2 ---"
python "$ANALYZER" "$PLAY" 3 2 --merge "$MERGE" $DRY_RUN

# Act 3, Scene 3
echo "--- Act 3, Scene 3 ---"
python "$ANALYZER" "$PLAY" 3 3 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 1
echo "--- Act 4, Scene 1 ---"
python "$ANALYZER" "$PLAY" 4 1 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 2
echo "--- Act 4, Scene 2 ---"
python "$ANALYZER" "$PLAY" 4 2 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 3
echo "--- Act 4, Scene 3 ---"
python "$ANALYZER" "$PLAY" 4 3 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 4
echo "--- Act 4, Scene 4 ---"
python "$ANALYZER" "$PLAY" 4 4 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 5
echo "--- Act 4, Scene 5 ---"
python "$ANALYZER" "$PLAY" 4 5 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 6
echo "--- Act 4, Scene 6 ---"
python "$ANALYZER" "$PLAY" 4 6 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 7
echo "--- Act 4, Scene 7 ---"
python "$ANALYZER" "$PLAY" 4 7 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 8
echo "--- Act 4, Scene 8 ---"
python "$ANALYZER" "$PLAY" 4 8 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 9
echo "--- Act 4, Scene 9 ---"
python "$ANALYZER" "$PLAY" 4 9 --merge "$MERGE" $DRY_RUN

# Act 4, Scene 10
echo "--- Act 4, Scene 10 ---"
python "$ANALYZER" "$PLAY" 4 10 --merge "$MERGE" $DRY_RUN

# Act 5, Scene 1
echo "--- Act 5, Scene 1 ---"
python "$ANALYZER" "$PLAY" 5 1 --merge "$MERGE" $DRY_RUN

# Act 5, Scene 2
echo "--- Act 5, Scene 2 ---"
python "$ANALYZER" "$PLAY" 5 2 --merge "$MERGE" $DRY_RUN

# Act 5, Scene 3
echo "--- Act 5, Scene 3 ---"
python "$ANALYZER" "$PLAY" 5 3 --merge "$MERGE" $DRY_RUN

echo ""
echo "=== Complete ==="
echo "Output directory: ~/utono/literature/glosses/henry-vi-part-2/"
