#!/bin/bash
# gloss-play_merchant-of-venice.sh - Analyze the entirety of Merchant of Venice
# Generated by /analyze-plays command
#
# Usage: ./gloss-play_merchant-of-venice.sh [OPTIONS] [FILTER]
#
# Options:
#   --status, -s    Show cache status for all scenes (what's done vs pending)
#   --dry-run, -n   Preview without API calls
#   --resume, -R    Skip scenes that are fully cached (resume interrupted run)
#   --validate, -V  Validate all scenes exist in play file before processing
#
# Filter (optional):
#   "Act I, Scene V"  - Process only Act 1, Scene 5
#   "Act I"           - Process all scenes in Act 1
#   "1 5" or "1.5"    - Process Act 1, Scene 5 (shorthand)
#
# Structure discovered:
#   - Opening Prologue: no
#   - Acts: 1, 2, 3, 4, 5
#   - Epilogue: no
#   - Total output files: 20

PLAY="/home/mlj/utono/literature/shakespeare-william/gutenberg/merchant_of_venice_gut.txt"
ANALYZER=~/utono/nvim-glosses-qa/python/scene_analyzer.py
MERGE=42
LOG_FILE=~/utono/nvim-glosses-qa/logs/scene_analyzer.log
DRY_RUN=""
STATUS_ONLY=""
RESUME_MODE=""
VALIDATE_MODE=""
FILTER_ACT=""
FILTER_SCENE=""

# Roman numeral conversion function
roman_to_int() {
    local roman="$1"
    case "${roman^^}" in
        I) echo 1 ;; II) echo 2 ;; III) echo 3 ;; IV) echo 4 ;; V) echo 5 ;;
        VI) echo 6 ;; VII) echo 7 ;; VIII) echo 8 ;; IX) echo 9 ;; X) echo 10 ;;
        FIRST) echo 1 ;; SECOND) echo 2 ;; THIRD) echo 3 ;; FOURTH) echo 4 ;; FIFTH) echo 5 ;;
        *) echo "$roman" ;;  # Assume it's already a number
    esac
}

# Parse command line arguments
for arg in "$@"; do
    case $arg in
        --status|-s)
            STATUS_ONLY="--status"
            ;;
        --dry-run|-n)
            DRY_RUN="--dry-run"
            ;;
        --resume|-R)
            RESUME_MODE="1"
            ;;
        --validate|-V)
            VALIDATE_MODE="1"
            ;;
        *)
            # Not a flag - treat as filter argument
            if [ -z "$FILTER_ACT" ]; then
                FILTER_ARG="$arg"
            fi
            ;;
    esac
done

# Parse filter argument if provided
if [ -n "$FILTER_ARG" ]; then
    # Handle formats: "Act I, Scene V", "Act 1 Scene 5", "1 5", "1.5", "Act I"
    # Extract act number
    if [[ "$FILTER_ARG" =~ [Aa][Cc][Tt][[:space:]]+([IVXivx]+|[0-9]+|FIRST|SECOND|THIRD|FOURTH|FIFTH) ]]; then
        FILTER_ACT=$(roman_to_int "${BASH_REMATCH[1]}")
    elif [[ "$FILTER_ARG" =~ ^([0-9]+)[[:space:].,:]+([0-9]+)$ ]]; then
        # Format: "1 5" or "1.5" or "1:5"
        FILTER_ACT="${BASH_REMATCH[1]}"
        FILTER_SCENE="${BASH_REMATCH[2]}"
    elif [[ "$FILTER_ARG" =~ ^([0-9]+)$ ]]; then
        # Just an act number
        FILTER_ACT="${BASH_REMATCH[1]}"
    fi

    # Extract scene number (if not already set)
    if [ -z "$FILTER_SCENE" ] && [[ "$FILTER_ARG" =~ [Ss][Cc][Ee][Nn][Ee][[:space:]]+([IVXivx]+|[0-9]+) ]]; then
        FILTER_SCENE=$(roman_to_int "${BASH_REMATCH[1]}")
    fi

    if [ -n "$FILTER_ACT" ]; then
        if [ -n "$FILTER_SCENE" ]; then
            echo "Filter: Act $FILTER_ACT, Scene $FILTER_SCENE only"
        else
            echo "Filter: Act $FILTER_ACT (all scenes)"
        fi
    else
        echo "Warning: Could not parse filter '$FILTER_ARG' - processing all scenes"
        FILTER_ARG=""
    fi
fi

# Function to check if scene matches filter
matches_filter() {
    local act=$1
    local scene=$2

    # No filter = process everything
    if [ -z "$FILTER_ACT" ]; then
        return 0
    fi

    # Check act match
    if [ "$act" != "$FILTER_ACT" ]; then
        return 1
    fi

    # If no scene filter, match all scenes in the act
    if [ -z "$FILTER_SCENE" ]; then
        return 0
    fi

    # Check scene match
    if [ "$scene" = "$FILTER_SCENE" ]; then
        return 0
    fi

    return 1
}

# Status mode: check cache status for all scenes
if [ -n "$STATUS_ONLY" ]; then
    echo "=== Merchant of Venice - Cache Status ==="
    echo ""
    CACHED=0
    PENDING=0

    # Act 1 Scene 1
    OUTPUT=$(python "$ANALYZER" "$PLAY" 1 1 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 1 Scene 1: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 1 Scene 1: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 1 Scene 2
    OUTPUT=$(python "$ANALYZER" "$PLAY" 1 2 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 1 Scene 2: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 1 Scene 2: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 1 Scene 3
    OUTPUT=$(python "$ANALYZER" "$PLAY" 1 3 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 1 Scene 3: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 1 Scene 3: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 2 Scene 1
    OUTPUT=$(python "$ANALYZER" "$PLAY" 2 1 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 1: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 1: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 2 Scene 2
    OUTPUT=$(python "$ANALYZER" "$PLAY" 2 2 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 2: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 2: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 2 Scene 3
    OUTPUT=$(python "$ANALYZER" "$PLAY" 2 3 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 3: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 3: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 2 Scene 4
    OUTPUT=$(python "$ANALYZER" "$PLAY" 2 4 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 4: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 4: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 2 Scene 5
    OUTPUT=$(python "$ANALYZER" "$PLAY" 2 5 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 5: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 5: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 2 Scene 6
    OUTPUT=$(python "$ANALYZER" "$PLAY" 2 6 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 6: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 6: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 2 Scene 7
    OUTPUT=$(python "$ANALYZER" "$PLAY" 2 7 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 7: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 7: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 2 Scene 8
    OUTPUT=$(python "$ANALYZER" "$PLAY" 2 8 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 8: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 8: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 2 Scene 9
    OUTPUT=$(python "$ANALYZER" "$PLAY" 2 9 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 9: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 2 Scene 9: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 3 Scene 1
    OUTPUT=$(python "$ANALYZER" "$PLAY" 3 1 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 3 Scene 1: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 3 Scene 1: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 3 Scene 2
    OUTPUT=$(python "$ANALYZER" "$PLAY" 3 2 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 3 Scene 2: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 3 Scene 2: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 3 Scene 3
    OUTPUT=$(python "$ANALYZER" "$PLAY" 3 3 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 3 Scene 3: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 3 Scene 3: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 3 Scene 4
    OUTPUT=$(python "$ANALYZER" "$PLAY" 3 4 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 3 Scene 4: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 3 Scene 4: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 3 Scene 5
    OUTPUT=$(python "$ANALYZER" "$PLAY" 3 5 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 3 Scene 5: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 3 Scene 5: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 4 Scene 1
    OUTPUT=$(python "$ANALYZER" "$PLAY" 4 1 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 4 Scene 1: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 4 Scene 1: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 4 Scene 2
    OUTPUT=$(python "$ANALYZER" "$PLAY" 4 2 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 4 Scene 2: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 4 Scene 2: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi
    # Act 5 Scene 1
    OUTPUT=$(python "$ANALYZER" "$PLAY" 5 1 --merge "$MERGE" --status 2>/dev/null)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 5 Scene 1: $CHUNKS chunks (cached)"
        ((CACHED++))
    else
        CHUNKS=$(echo "$OUTPUT" | grep -oP '\d+ chunks' | head -1 | grep -oP '\d+' || echo "?")
        echo "Act 5 Scene 1: $CHUNKS chunks (0 cached, $CHUNKS to process)"
        ((PENDING++))
    fi

    echo ""
    echo "=== Summary ==="
    echo "Cached: $CACHED scenes"
    echo "Pending: $PENDING scenes"
    if [ "$PENDING" -eq 0 ]; then
        echo "All scenes cached - nothing to process"
    else
        echo "Run without --status to process pending scenes"
    fi
    exit 0
fi

# Validate mode: check all scenes exist before processing
if [ -n "$VALIDATE_MODE" ]; then
    echo "=== Merchant of Venice - Validating Script ==="
    echo ""
    VALID=0
    INVALID=0

    if python "$ANALYZER" "$PLAY" 1 1 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 1 Scene 1"
    else
        ((INVALID++))
        echo "  ✗ Act 1 Scene 1 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 1 2 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 1 Scene 2"
    else
        ((INVALID++))
        echo "  ✗ Act 1 Scene 2 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 1 3 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 1 Scene 3"
    else
        ((INVALID++))
        echo "  ✗ Act 1 Scene 3 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 2 1 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 2 Scene 1"
    else
        ((INVALID++))
        echo "  ✗ Act 2 Scene 1 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 2 2 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 2 Scene 2"
    else
        ((INVALID++))
        echo "  ✗ Act 2 Scene 2 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 2 3 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 2 Scene 3"
    else
        ((INVALID++))
        echo "  ✗ Act 2 Scene 3 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 2 4 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 2 Scene 4"
    else
        ((INVALID++))
        echo "  ✗ Act 2 Scene 4 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 2 5 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 2 Scene 5"
    else
        ((INVALID++))
        echo "  ✗ Act 2 Scene 5 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 2 6 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 2 Scene 6"
    else
        ((INVALID++))
        echo "  ✗ Act 2 Scene 6 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 2 7 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 2 Scene 7"
    else
        ((INVALID++))
        echo "  ✗ Act 2 Scene 7 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 2 8 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 2 Scene 8"
    else
        ((INVALID++))
        echo "  ✗ Act 2 Scene 8 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 2 9 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 2 Scene 9"
    else
        ((INVALID++))
        echo "  ✗ Act 2 Scene 9 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 3 1 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 3 Scene 1"
    else
        ((INVALID++))
        echo "  ✗ Act 3 Scene 1 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 3 2 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 3 Scene 2"
    else
        ((INVALID++))
        echo "  ✗ Act 3 Scene 2 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 3 3 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 3 Scene 3"
    else
        ((INVALID++))
        echo "  ✗ Act 3 Scene 3 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 3 4 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 3 Scene 4"
    else
        ((INVALID++))
        echo "  ✗ Act 3 Scene 4 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 3 5 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 3 Scene 5"
    else
        ((INVALID++))
        echo "  ✗ Act 3 Scene 5 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 4 1 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 4 Scene 1"
    else
        ((INVALID++))
        echo "  ✗ Act 4 Scene 1 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 4 2 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 4 Scene 2"
    else
        ((INVALID++))
        echo "  ✗ Act 4 Scene 2 - NOT FOUND"
    fi
    if python "$ANALYZER" "$PLAY" 5 1 --validate 2>/dev/null; then
        ((VALID++))
        echo "  ✓ Act 5 Scene 1"
    else
        ((INVALID++))
        echo "  ✗ Act 5 Scene 1 - NOT FOUND"
    fi

    echo ""
    echo "=== Validation Summary ==="
    echo "Found: $VALID scenes"
    echo "Missing: $INVALID scenes"
    if [ "$INVALID" -eq 0 ]; then
        echo "All scenes validated - script is correct"
        exit 0
    else
        echo ""
        echo "[CLAUDE_ACTION_REQUIRED]"
        echo "$INVALID scene(s) not found in play file."
        echo "Script may need regeneration with /analyze-plays"
        exit 1
    fi
fi

if [ -n "$DRY_RUN" ]; then
    echo "=== DRY RUN MODE ==="
fi

if [ -n "$RESUME_MODE" ]; then
    echo "=== RESUME MODE ==="
    echo "Checking cache status before each scene..."
    echo ""
fi

# Clear log file at start of run (unless resuming - append instead)
mkdir -p "$(dirname "$LOG_FILE")"
if [ -n "$RESUME_MODE" ]; then
    echo "" >> "$LOG_FILE"
    echo "=== Resuming at $(date) ===" >> "$LOG_FILE"
else
    > "$LOG_FILE"
    echo "Log cleared: $LOG_FILE"
fi

# Error tracking
ERRORS=0
FAILED_SCENES=""
SUCCESSFUL=0
SKIPPED=0
TOTAL_SCENES=20

echo "Analyzing Merchant of Venice..."
echo "Play file: $PLAY"
echo "Merge threshold: $MERGE lines"
echo "Log file: $LOG_FILE"
echo "Total scenes: $TOTAL_SCENES"
echo ""

# Act 1, Scene 1
if matches_filter 1 1; then
    echo "--- Act 1, Scene 1 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 1 1 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 1, Scene 1 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 1 1 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 1 Scene 1: exit code $?"
                echo "[FAILED] Act 1, Scene 1"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 1 1 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 1 Scene 1: exit code $?"
            echo "[FAILED] Act 1, Scene 1"
        fi
    fi
fi
# Act 1, Scene 2
if matches_filter 1 2; then
    echo "--- Act 1, Scene 2 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 1 2 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 1, Scene 2 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 1 2 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 1 Scene 2: exit code $?"
                echo "[FAILED] Act 1, Scene 2"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 1 2 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 1 Scene 2: exit code $?"
            echo "[FAILED] Act 1, Scene 2"
        fi
    fi
fi
# Act 1, Scene 3
if matches_filter 1 3; then
    echo "--- Act 1, Scene 3 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 1 3 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 1, Scene 3 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 1 3 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 1 Scene 3: exit code $?"
                echo "[FAILED] Act 1, Scene 3"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 1 3 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 1 Scene 3: exit code $?"
            echo "[FAILED] Act 1, Scene 3"
        fi
    fi
fi
# Act 2, Scene 1
if matches_filter 2 1; then
    echo "--- Act 2, Scene 1 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 2 1 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 2, Scene 1 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 2 1 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 1: exit code $?"
                echo "[FAILED] Act 2, Scene 1"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 2 1 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 1: exit code $?"
            echo "[FAILED] Act 2, Scene 1"
        fi
    fi
fi
# Act 2, Scene 2
if matches_filter 2 2; then
    echo "--- Act 2, Scene 2 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 2 2 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 2, Scene 2 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 2 2 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 2: exit code $?"
                echo "[FAILED] Act 2, Scene 2"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 2 2 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 2: exit code $?"
            echo "[FAILED] Act 2, Scene 2"
        fi
    fi
fi
# Act 2, Scene 3
if matches_filter 2 3; then
    echo "--- Act 2, Scene 3 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 2 3 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 2, Scene 3 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 2 3 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 3: exit code $?"
                echo "[FAILED] Act 2, Scene 3"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 2 3 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 3: exit code $?"
            echo "[FAILED] Act 2, Scene 3"
        fi
    fi
fi
# Act 2, Scene 4
if matches_filter 2 4; then
    echo "--- Act 2, Scene 4 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 2 4 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 2, Scene 4 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 2 4 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 4: exit code $?"
                echo "[FAILED] Act 2, Scene 4"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 2 4 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 4: exit code $?"
            echo "[FAILED] Act 2, Scene 4"
        fi
    fi
fi
# Act 2, Scene 5
if matches_filter 2 5; then
    echo "--- Act 2, Scene 5 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 2 5 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 2, Scene 5 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 2 5 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 5: exit code $?"
                echo "[FAILED] Act 2, Scene 5"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 2 5 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 5: exit code $?"
            echo "[FAILED] Act 2, Scene 5"
        fi
    fi
fi
# Act 2, Scene 6
if matches_filter 2 6; then
    echo "--- Act 2, Scene 6 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 2 6 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 2, Scene 6 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 2 6 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 6: exit code $?"
                echo "[FAILED] Act 2, Scene 6"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 2 6 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 6: exit code $?"
            echo "[FAILED] Act 2, Scene 6"
        fi
    fi
fi
# Act 2, Scene 7
if matches_filter 2 7; then
    echo "--- Act 2, Scene 7 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 2 7 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 2, Scene 7 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 2 7 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 7: exit code $?"
                echo "[FAILED] Act 2, Scene 7"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 2 7 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 7: exit code $?"
            echo "[FAILED] Act 2, Scene 7"
        fi
    fi
fi
# Act 2, Scene 8
if matches_filter 2 8; then
    echo "--- Act 2, Scene 8 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 2 8 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 2, Scene 8 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 2 8 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 8: exit code $?"
                echo "[FAILED] Act 2, Scene 8"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 2 8 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 8: exit code $?"
            echo "[FAILED] Act 2, Scene 8"
        fi
    fi
fi
# Act 2, Scene 9
if matches_filter 2 9; then
    echo "--- Act 2, Scene 9 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 2 9 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 2, Scene 9 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 2 9 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 9: exit code $?"
                echo "[FAILED] Act 2, Scene 9"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 2 9 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 9: exit code $?"
            echo "[FAILED] Act 2, Scene 9"
        fi
    fi
fi
# Act 3, Scene 1
if matches_filter 3 1; then
    echo "--- Act 3, Scene 1 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 3 1 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 3, Scene 1 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 3 1 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 1: exit code $?"
                echo "[FAILED] Act 3, Scene 1"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 3 1 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 1: exit code $?"
            echo "[FAILED] Act 3, Scene 1"
        fi
    fi
fi
# Act 3, Scene 2
if matches_filter 3 2; then
    echo "--- Act 3, Scene 2 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 3 2 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 3, Scene 2 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 3 2 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 2: exit code $?"
                echo "[FAILED] Act 3, Scene 2"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 3 2 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 2: exit code $?"
            echo "[FAILED] Act 3, Scene 2"
        fi
    fi
fi
# Act 3, Scene 3
if matches_filter 3 3; then
    echo "--- Act 3, Scene 3 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 3 3 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 3, Scene 3 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 3 3 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 3: exit code $?"
                echo "[FAILED] Act 3, Scene 3"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 3 3 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 3: exit code $?"
            echo "[FAILED] Act 3, Scene 3"
        fi
    fi
fi
# Act 3, Scene 4
if matches_filter 3 4; then
    echo "--- Act 3, Scene 4 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 3 4 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 3, Scene 4 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 3 4 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 4: exit code $?"
                echo "[FAILED] Act 3, Scene 4"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 3 4 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 4: exit code $?"
            echo "[FAILED] Act 3, Scene 4"
        fi
    fi
fi
# Act 3, Scene 5
if matches_filter 3 5; then
    echo "--- Act 3, Scene 5 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 3 5 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 3, Scene 5 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 3 5 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 5: exit code $?"
                echo "[FAILED] Act 3, Scene 5"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 3 5 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 5: exit code $?"
            echo "[FAILED] Act 3, Scene 5"
        fi
    fi
fi
# Act 4, Scene 1
if matches_filter 4 1; then
    echo "--- Act 4, Scene 1 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 4 1 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 4, Scene 1 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 4 1 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 4 Scene 1: exit code $?"
                echo "[FAILED] Act 4, Scene 1"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 4 1 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 4 Scene 1: exit code $?"
            echo "[FAILED] Act 4, Scene 1"
        fi
    fi
fi
# Act 4, Scene 2
if matches_filter 4 2; then
    echo "--- Act 4, Scene 2 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 4 2 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 4, Scene 2 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 4 2 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 4 Scene 2: exit code $?"
                echo "[FAILED] Act 4, Scene 2"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 4 2 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 4 Scene 2: exit code $?"
            echo "[FAILED] Act 4, Scene 2"
        fi
    fi
fi
# Act 5, Scene 1
if matches_filter 5 1; then
    echo "--- Act 5, Scene 1 ---"
    if [ -n "$RESUME_MODE" ]; then
        if python "$ANALYZER" "$PLAY" 5 1 --merge "$MERGE" --status 2>/dev/null; then
            echo "[SKIPPED] Act 5, Scene 1 - fully cached"
            ((SKIPPED++))
        else
            if python "$ANALYZER" "$PLAY" 5 1 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
                ((SUCCESSFUL++))
            else
                ((ERRORS++))
                FAILED_SCENES="$FAILED_SCENES
  Act 5 Scene 1: exit code $?"
                echo "[FAILED] Act 5, Scene 1"
            fi
        fi
    else
        if python "$ANALYZER" "$PLAY" 5 1 --merge "$MERGE" $DRY_RUN 2>&1 | tee -a "$LOG_FILE"; then
            ((SUCCESSFUL++))
        else
            ((ERRORS++))
            FAILED_SCENES="$FAILED_SCENES
  Act 5 Scene 1: exit code $?"
            echo "[FAILED] Act 5, Scene 1"
        fi
    fi
fi

# Summary
echo ""
echo "=== ANALYSIS SUMMARY ==="
echo "Play: Merchant of Venice"
echo "Total scenes: $TOTAL_SCENES"
echo "Successful: $SUCCESSFUL"
if [ -n "$RESUME_MODE" ]; then
    echo "Skipped (cached): $SKIPPED"
fi
echo "Failed: $ERRORS"

if [ "$ERRORS" -gt 0 ]; then
    echo ""
    echo "[FAILED SCENES]"
    echo "$FAILED_SCENES"
    echo ""
    echo "[CLAUDE_ACTION_REQUIRED]"
    echo "$ERRORS scene(s) failed. Review errors above and in log file:"
    echo "  $LOG_FILE"
    echo ""
    echo "Suggested actions:"
    echo "1. Check log file for detailed error messages"
    echo "2. Run failed scenes individually to diagnose"
    echo "3. Use --resume to retry only failed/pending scenes"
    exit 1
else
    echo ""
    if [ -n "$RESUME_MODE" ] && [ "$SKIPPED" -gt 0 ]; then
        echo "Resume complete! $SKIPPED scenes were already cached."
    else
        echo "All scenes processed successfully!"
    fi
    echo "Output directory: ~/utono/literature/glosses/merchant-of-venice/"
    exit 0
fi
