#!/bin/bash
# gloss-play_henry-v.sh - Analyze the entirety of Henry V
# Generated by /analyze-plays command
#
# Usage: ./gloss-play_henry-v.sh [--status] [--dry-run] [--resume] [--validate]
#
# Options:
#   --status, -s    Show cache status for all scenes (what's done vs pending)
#   --dry-run, -n   Preview without API calls
#   --resume, -R    Skip scenes that are fully cached (resume interrupted run)
#   --validate, -V  Validate all scenes exist in play file before processing
#
# Structure discovered:
#   - Opening Prologue: yes
#   - Acts: 1, 2, 3, 4, 5
#   - Prologues: 5
#   - Epilogue: yes
#   - Total output files: 29

PLAY="/home/mlj/utono/literature/shakespeare-william/gutenberg/henry_v_gut.txt"
ANALYZER=~/utono/nvim-glosses-qa/python/scene_analyzer.py
MERGE=42
LOG_FILE=~/utono/nvim-glosses-qa/logs/scene_analyzer.log
DRY_RUN=""
STATUS_ONLY=""
RESUME_MODE=""
VALIDATE_MODE=""

# Parse command line arguments
for arg in "$@"; do
    case $arg in
        --status|-s)
            STATUS_ONLY="--status"
            ;;
        --dry-run|-n)
            DRY_RUN="--dry-run"
            ;;
        --resume|-R)
            RESUME_MODE="1"
            ;;
        --validate|-V)
            VALIDATE_MODE="1"
            ;;
    esac
done

# Status mode: check cache status for all scenes
if [ -n "$STATUS_ONLY" ]; then
    echo "=== Henry V - Cache Status ==="
    echo ""
    CACHED=0
    PENDING=0

    if python "$ANALYZER" "$PLAY" 0 0 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 1 1 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 1 2 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 2 0 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 2 1 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 2 2 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 2 3 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 2 4 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 3 0 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 3 1 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 3 2 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 3 3 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 3 4 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 3 5 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 3 6 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 3 7 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 4 0 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 4 1 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 4 2 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 4 3 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 4 4 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 4 5 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 4 6 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 4 7 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 4 8 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 5 0 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 5 1 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" 5 2 --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    if python "$ANALYZER" "$PLAY" Epilogue --merge "$MERGE" --status 2>/dev/null; then
    ((CACHED++))
else
    ((PENDING++))
fi

    echo ""
    echo "=== Summary ==="
    echo "Cached: $CACHED scenes"
    echo "Pending: $PENDING scenes"
    if [ "$PENDING" -eq 0 ]; then
        echo "All scenes cached - nothing to process"
    else
        echo "Run without --status to process pending scenes"
    fi
    exit 0
fi

# Validate mode: check all scenes exist before processing
if [ -n "$VALIDATE_MODE" ]; then
    echo "=== Henry V - Validating Script ==="
    echo ""
    VALID=0
    INVALID=0

    if python "$ANALYZER" "$PLAY" 0 0 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Prologue (Opening) - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 1 1 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 1, Scene 1 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 1 2 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 1, Scene 2 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 2 0 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 2, Prologue - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 2 1 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 2, Scene 1 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 2 2 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 2, Scene 2 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 2 3 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 2, Scene 3 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 2 4 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 2, Scene 4 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 3 0 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 3, Prologue - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 3 1 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 3, Scene 1 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 3 2 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 3, Scene 2 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 3 3 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 3, Scene 3 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 3 4 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 3, Scene 4 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 3 5 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 3, Scene 5 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 3 6 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 3, Scene 6 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 3 7 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 3, Scene 7 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 4 0 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 4, Prologue - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 4 1 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 4, Scene 1 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 4 2 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 4, Scene 2 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 4 3 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 4, Scene 3 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 4 4 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 4, Scene 4 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 4 5 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 4, Scene 5 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 4 6 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 4, Scene 6 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 4 7 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 4, Scene 7 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 4 8 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 4, Scene 8 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 5 0 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 5, Prologue - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 5 1 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 5, Scene 1 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" 5 2 --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Act 5, Scene 2 - NOT FOUND"
fi

    if python "$ANALYZER" "$PLAY" Epilogue --validate 2>/dev/null; then
    ((VALID++))
else
    ((INVALID++))
    echo "  ✗ Epilogue - NOT FOUND"
fi

    echo ""
    echo "=== Validation Summary ==="
    echo "Found: $VALID scenes"
    echo "Missing: $INVALID scenes"
    if [ "$INVALID" -eq 0 ]; then
        echo "All scenes validated - script is correct"
        exit 0
    else
        echo ""
        echo "[CLAUDE_ACTION_REQUIRED]"
        echo "$INVALID scene(s) not found in play file."
        echo "Script may need regeneration with /analyze-plays"
        exit 1
    fi
fi

if [ -n "$DRY_RUN" ]; then
    echo "=== DRY RUN MODE ==="
fi

if [ -n "$RESUME_MODE" ]; then
    echo "=== RESUME MODE ==="
    echo "Checking cache status before each scene..."
    echo ""
fi

# Clear log file at start of run (unless resuming - append instead)
mkdir -p "$(dirname "$LOG_FILE")"
if [ -n "$RESUME_MODE" ]; then
    echo "" >> "$LOG_FILE"
    echo "=== Resuming at $(date) ===" >> "$LOG_FILE"
else
    > "$LOG_FILE"
    echo "Log cleared: $LOG_FILE"
fi

# Error tracking
ERRORS=0
FAILED_SCENES=""
SUCCESSFUL=0
SKIPPED=0
TOTAL_SCENES=29

echo "Analyzing Henry V..."
echo "Play file: $PLAY"
echo "Merge threshold: $MERGE lines"
echo "Log file: $LOG_FILE"
echo "Total scenes: $TOTAL_SCENES"
echo ""

# Opening Prologue
echo "--- Prologue (Opening) ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 0 0 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Prologue (Opening) - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 0 0 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Prologue: exit code $?"
    echo "[FAILED] Prologue (Opening)"
fi
echo ""

# Act 1
echo "--- Act 1, Scene 1 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 1 1 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 1, Scene 1 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 1 1 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 1 Scene 1: exit code $?"
    echo "[FAILED] Act 1, Scene 1"
fi
echo ""
echo "--- Act 1, Scene 2 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 1 2 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 1, Scene 2 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 1 2 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 1 Scene 2: exit code $?"
    echo "[FAILED] Act 1, Scene 2"
fi
echo ""

# Act 2
echo "--- Act 2, Prologue ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 2 0 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 2, Prologue - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 2 0 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 2 Prologue: exit code $?"
    echo "[FAILED] Act 2, Prologue"
fi
echo ""
echo "--- Act 2, Scene 1 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 2 1 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 2, Scene 1 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 2 1 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 1: exit code $?"
    echo "[FAILED] Act 2, Scene 1"
fi
echo ""
echo "--- Act 2, Scene 2 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 2 2 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 2, Scene 2 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 2 2 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 2: exit code $?"
    echo "[FAILED] Act 2, Scene 2"
fi
echo ""
echo "--- Act 2, Scene 3 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 2 3 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 2, Scene 3 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 2 3 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 3: exit code $?"
    echo "[FAILED] Act 2, Scene 3"
fi
echo ""
echo "--- Act 2, Scene 4 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 2 4 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 2, Scene 4 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 2 4 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 2 Scene 4: exit code $?"
    echo "[FAILED] Act 2, Scene 4"
fi
echo ""

# Act 3
echo "--- Act 3, Prologue ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 3 0 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 3, Prologue - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 3 0 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 3 Prologue: exit code $?"
    echo "[FAILED] Act 3, Prologue"
fi
echo ""
echo "--- Act 3, Scene 1 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 3 1 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 3, Scene 1 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 3 1 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 1: exit code $?"
    echo "[FAILED] Act 3, Scene 1"
fi
echo ""
echo "--- Act 3, Scene 2 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 3 2 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 3, Scene 2 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 3 2 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 2: exit code $?"
    echo "[FAILED] Act 3, Scene 2"
fi
echo ""
echo "--- Act 3, Scene 3 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 3 3 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 3, Scene 3 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 3 3 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 3: exit code $?"
    echo "[FAILED] Act 3, Scene 3"
fi
echo ""
echo "--- Act 3, Scene 4 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 3 4 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 3, Scene 4 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 3 4 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 4: exit code $?"
    echo "[FAILED] Act 3, Scene 4"
fi
echo ""
echo "--- Act 3, Scene 5 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 3 5 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 3, Scene 5 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 3 5 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 5: exit code $?"
    echo "[FAILED] Act 3, Scene 5"
fi
echo ""
echo "--- Act 3, Scene 6 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 3 6 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 3, Scene 6 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 3 6 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 6: exit code $?"
    echo "[FAILED] Act 3, Scene 6"
fi
echo ""
echo "--- Act 3, Scene 7 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 3 7 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 3, Scene 7 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 3 7 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 3 Scene 7: exit code $?"
    echo "[FAILED] Act 3, Scene 7"
fi
echo ""

# Act 4
echo "--- Act 4, Prologue ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 4 0 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 4, Prologue - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 4 0 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 4 Prologue: exit code $?"
    echo "[FAILED] Act 4, Prologue"
fi
echo ""
echo "--- Act 4, Scene 1 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 4 1 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 4, Scene 1 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 4 1 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 4 Scene 1: exit code $?"
    echo "[FAILED] Act 4, Scene 1"
fi
echo ""
echo "--- Act 4, Scene 2 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 4 2 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 4, Scene 2 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 4 2 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 4 Scene 2: exit code $?"
    echo "[FAILED] Act 4, Scene 2"
fi
echo ""
echo "--- Act 4, Scene 3 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 4 3 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 4, Scene 3 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 4 3 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 4 Scene 3: exit code $?"
    echo "[FAILED] Act 4, Scene 3"
fi
echo ""
echo "--- Act 4, Scene 4 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 4 4 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 4, Scene 4 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 4 4 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 4 Scene 4: exit code $?"
    echo "[FAILED] Act 4, Scene 4"
fi
echo ""
echo "--- Act 4, Scene 5 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 4 5 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 4, Scene 5 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 4 5 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 4 Scene 5: exit code $?"
    echo "[FAILED] Act 4, Scene 5"
fi
echo ""
echo "--- Act 4, Scene 6 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 4 6 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 4, Scene 6 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 4 6 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 4 Scene 6: exit code $?"
    echo "[FAILED] Act 4, Scene 6"
fi
echo ""
echo "--- Act 4, Scene 7 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 4 7 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 4, Scene 7 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 4 7 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 4 Scene 7: exit code $?"
    echo "[FAILED] Act 4, Scene 7"
fi
echo ""
echo "--- Act 4, Scene 8 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 4 8 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 4, Scene 8 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 4 8 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 4 Scene 8: exit code $?"
    echo "[FAILED] Act 4, Scene 8"
fi
echo ""

# Act 5
echo "--- Act 5, Prologue ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 5 0 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 5, Prologue - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 5 0 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 5 Prologue: exit code $?"
    echo "[FAILED] Act 5, Prologue"
fi
echo ""
echo "--- Act 5, Scene 1 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 5 1 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 5, Scene 1 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 5 1 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 5 Scene 1: exit code $?"
    echo "[FAILED] Act 5, Scene 1"
fi
echo ""
echo "--- Act 5, Scene 2 ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" 5 2 --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Act 5, Scene 2 - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" 5 2 --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Act 5 Scene 2: exit code $?"
    echo "[FAILED] Act 5, Scene 2"
fi
echo ""

# Epilogue
echo "--- Epilogue ---"
if [ -n "$RESUME_MODE" ] && python "$ANALYZER" "$PLAY" Epilogue --merge "$MERGE" --status 2>/dev/null; then
    echo "[SKIPPED] Epilogue - fully cached"
    ((SKIPPED++))
elif python "$ANALYZER" "$PLAY" Epilogue --merge "$MERGE" $DRY_RUN; then
    ((SUCCESSFUL++))
else
    ((ERRORS++))
    FAILED_SCENES="$FAILED_SCENES
  Epilogue: exit code $?"
    echo "[FAILED] Epilogue"
fi
echo ""

# Summary
echo ""
echo "=== ANALYSIS SUMMARY ==="
echo "Play: Henry V"
echo "Total scenes: $TOTAL_SCENES"
echo "Successful: $SUCCESSFUL"
if [ -n "$RESUME_MODE" ]; then
    echo "Skipped (cached): $SKIPPED"
fi
echo "Failed: $ERRORS"

if [ "$ERRORS" -gt 0 ]; then
    echo ""
    echo "[FAILED SCENES]"
    echo "$FAILED_SCENES"
    echo ""
    echo "[CLAUDE_ACTION_REQUIRED]"
    echo "$ERRORS scene(s) failed. Review errors above and in log file:"
    echo "  $LOG_FILE"
    echo ""
    echo "Suggested actions:"
    echo "1. Check log file for detailed error messages"
    echo "2. Run failed scenes individually to diagnose"
    echo "3. Use --resume to retry only failed/pending scenes"
    exit 1
else
    echo ""
    if [ -n "$RESUME_MODE" ] && [ "$SKIPPED" -gt 0 ]; then
        echo "Resume complete! $SKIPPED scenes were already cached."
    else
        echo "All scenes processed successfully!"
    fi
    echo "Output directory: ~/utono/literature/glosses/henry-v/"
    exit 0
fi
